In [1]:
a= 2
print (a)
print(type(a))
b= float(a)
print(b) 



2
<class 'int'>
2.0


In [2]:
a="Hello World"
print(a[2:6])
print(a[:6])
print(a[2:])

llo 
Hello 
llo World


In [3]:
a="Hello Serena"
print(a.upper())
print(a.lower())

HELLO SERENA
hello serena


In [4]:
a="     Saritha    "
print(a.strip())
print(a)

Saritha
     Saritha    


In [5]:
a="  Jerena is a good "
print(a.strip())
b= a.strip()
print(b.replace("Jerena","Serena"))



Jerena is a good
Serena is a good


In [6]:
a= " Hello everyone this is serena"
print(a.split())

['Hello', 'everyone', 'this', 'is', 'serena']


print(""helo)

In [7]:
a="Hello "
b="World"
print(a+b)
c1= ''.join([a,b])
print(c1)

Hello World
Hello World


In [8]:
a=36
b= "Her age is {}"
print(b.format(a))

Her age is 36


In [9]:
a= 8
b= 50
c= 10
d="I want {} chocolates for {} rupees in {} time."
print(d.format(a,b,c))

I want 8 chocolates for 50 rupees in 10 time.


In [10]:
txt="This is my \" First\" class"
print(txt)

This is my " First" class


In [11]:
#Lists

In [12]:
myList=["apple","banana","orange"]
print(myList)

['apple', 'banana', 'orange']


In [13]:
print(len(myList))

3


In [14]:
myList1=["a",3,4,7,"b","c",5,34]
print (myList1[2:7])
print(myList1[2])
print(myList1[5])


[4, 7, 'b', 'c', 5]
4
c


In [15]:
myList=["apple","grapes","fig","orange"]
myList[2]= "greenapple"
print(myList)

['apple', 'grapes', 'greenapple', 'orange']


In [16]:
myList=["apple","grapes","fig","orange","muskmelon"]
myList[2:5]=["Greenapple","watermelon"]
print(myList)

['apple', 'grapes', 'Greenapple', 'watermelon']


In [17]:
thisList=["apple","grapes","fig","orange","muskmelon"]
thisList.insert(1,"kiwi")
print(thisList)

['apple', 'kiwi', 'grapes', 'fig', 'orange', 'muskmelon']


In [18]:
thisList=["apple","grapes","fig","orange","muskmelon"]
thisList.append("kiwi")
print(thisList)

['apple', 'grapes', 'fig', 'orange', 'muskmelon', 'kiwi']


In [19]:
l1=[1,2,3,4]
l2=[2,4,6,8,0]
l1.extend(l2)
print(l1)

[1, 2, 3, 4, 2, 4, 6, 8, 0]


In [20]:
thisList=["apple","fig"]
thisList.remove("fig")
print(thisList)

['apple']


In [21]:
thisList=["apple","grapes","fig","orange","muskmelon"]
thisList.pop(1)
print(thisList)

['apple', 'fig', 'orange', 'muskmelon']


In [22]:
thisList=["apple","grapes","fig","orange","muskmelon"]
thisList.pop()
print(thisList)

['apple', 'grapes', 'fig', 'orange']


In [23]:
thisList=["apple","grapes","fig","orange","muskmelon"]
del thisList[2]
print(thisList)

['apple', 'grapes', 'orange', 'muskmelon']


In [24]:
thisList=["apple","grapes","fig","orange","muskmelon"]
del thisList
print(thisList)

NameError: name 'thisList' is not defined

In [ ]:
thisList=["apple","grapes","fig","orange","muskmelon"]
thisList.clear()
print(thisList)
#the elements in the list is cleared but the list remains.

[]


In [ ]:
thisList=["apple","grapes","fig","orange","muskmelon"]


for a in thisList:
     print(a)

apple
grapes
fig
orange
muskmelon


In [ ]:
thisList=["apple","grapes","fig","orange","muskmelon"]

for i in range (len(thisList)):
    print(i)
for i in range (len(thisList)):
    print(thisList[i])
 

0
1
2
3
4
apple
grapes
fig
orange
muskmelon


In [ ]:
for i in range (10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
thisList=["blue","black","greeen","yellow"]
newList=[]

for x in thisList:
    if "b" in x:
        newList.append(x)

print(newList)

thisList=["blue","black","greeen","yellow"]

newList=[x for x in thisList if "b" in x]
print(newList)

    

['blue', 'black']
['blue', 'black']


In [ ]:
thislist=["nose","eye","neck","back"]
newList=[]

for x in thislist:
    if "ck"in x:
        newList.append(x)
print(newList)

thislist=["nose","eye","neck","back"]
newList=[x for x in thislist if "ck" in x]
print(newList)

['neck', 'back']
['neck', 'back']


In [ ]:
haha=[x for x in range(5)]
print(haha)

[0, 1, 2, 3, 4]


In [ ]:
thislist=["nose","eye","neck","back"]
newList=[x.upper() for x in thisList]
print(newList)

['BLUE', 'BLACK', 'GREEEN', 'YELLOW']


In [ ]:
thislist=["Nose","Eye","Neck","Back"]
newList=[a.lower() for a in thisList ]
print(newList)


['blue', 'black', 'greeen', 'yellow']


In [ ]:
thisList=["blue","black","greeen","yellow"]

thisList.sort()
print(thisList)

thisList.sort(reverse=True)
print(thisList)

['black', 'blue', 'greeen', 'yellow']
['yellow', 'greeen', 'blue', 'black']


In [ ]:
l1=[2,67,45,136,0,48]

l1.sort()
print(l1)

l1.sort(reverse=True)
print(l1)


[0, 2, 45, 48, 67, 136]
[136, 67, 48, 45, 2, 0]


In [ ]:
thisList=["blue","black","greeen","yellow"]
myList=thisList.copy()
print(myList)

['blue', 'black', 'greeen', 'yellow']


In [ ]:
#tuples

In [ ]:
thistupple=("sansa","saritha","zelia","simon","serena")
print(thistupple)

('sansa', 'saritha', 'zelia', 'simon', 'serena')


In [ ]:
thistupple=("sansa","saritha","zelia","simon","serena")
print(thistupple[2:])
print(thistupple[:5])
print(thistupple[3:6])

('zelia', 'simon', 'serena')
('sansa', 'saritha', 'zelia', 'simon', 'serena')
('simon', 'serena')


In [ ]:
thistupple=("sansa","saritha","zelia","simon","serena")
thistupple[2]="anvesh"

TypeError: 'tuple' object does not support item assignment

In [ ]:
x=("sansa","saritha","zelia","simon","serena")
y=list(x)
y[2]="anvesh"
x=tuple(y)
print(x)

('sansa', 'saritha', 'anvesh', 'simon', 'serena')


In [ ]:
thistupple=("sansa","saritha","zelia","simon","serena")
for a in thistupple:
    print(a)

sansa
saritha
zelia
simon
serena


In [ ]:
for i in range (len(thistupple)):
    print(i)


0
1
2
3
4


In [ ]:
def generate_nine():
       return 9
print(generate_nine())

9


In [ ]:
t1=("a","b","c")
t2=(1,2,3)
t3=t1+t2
print(t3)

('a', 'b', 'c', 1, 2, 3)


In [ ]:
#sets

In [ ]:
thisSet={"pen","pencil","scale","eraser"}
print(thisSet)

{'pencil', 'scale', 'eraser', 'pen'}


In [ ]:
thisSet={"pen","pencil","scale","eraser","pen"}
print(thisSet)

{'pencil', 'scale', 'eraser', 'pen'}


In [ ]:
print(len(thisSet))

4


In [ ]:
thisSet={"pen","pencil","scale","eraser"}

for a in thisSet:
    print(a)

pencil
scale
eraser
pen


In [ ]:
thisSet.add("bag")
print(thisSet)

{'pencil', 'pen', 'scale', 'bag', 'eraser'}


In [ ]:
thisSet.remove("pencil")
print(thisSet)

{'pen', 'scale', 'bag', 'eraser'}


In [ ]:
#dictionaries

In [ ]:
thisDict={
    "Brand":"Nyka",
    "Model":"lipstick",
    "year": 2020
}
print(thisDict)

{'Brand': 'Nyka', 'Model': 'lipstick', 'year': 2020}


In [ ]:
thisdict={
    "brand":"Ford",
    "model":"Mustang",
    "year":1964,
    "year": 2020
    
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}


In [ ]:
print(len(thisdict))

3


In [ ]:
thisdict={
    "brand":"Ford",
    "model":"Mustang",
    "year":1964,
    "Colour": ["green","yellow","blue"]
    
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'Colour': ['green', 'yellow', 'blue']}


In [ ]:
thisdict["brand"]

'Ford'

In [ ]:
print(thisdict.keys())

dict_keys(['brand', 'model', 'year', 'Colour'])


In [ ]:
print(thisdict.values())

dict_values(['Ford', 'Mustang', 1964, ['green', 'yellow', 'blue']])


In [ ]:
print(thisdict.items())

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964), ('Colour', ['green', 'yellow', 'blue'])])


In [ ]:
thisdict.update({"year":1965})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1965, 'Colour': ['green', 'yellow', 'blue']}


In [ ]:
thisdict.update({"mileage": 25})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1965, 'Colour': ['green', 'yellow', 'blue'], 'mileage': 25}


In [ ]:
thisdict.pop("mileage")
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1965, 'Colour': ['green', 'yellow', 'blue']}


In [ ]:
def my_function():
    print("Hello World")

my_function()

Hello World


In [ ]:
def my_function(fname):
    print(fname+" Mendanha")
my_function("Serena")

Serena Mendanha


In [ ]:
def my_function(x):
    return 5**x
print(my_function(3))

125


In [ ]:
#lambda function

In [ ]:
x= lambda a:a+30
print(x(5))

35


In [ ]:
x=lambda a,b,c:a*b*c
print(x(3,5,8))

120


In [ ]:
# Write a python program to summ all the items in a list

l1=[2,3,4,5,6,7]
sum=0
for x in l1:
    sum+=x
print(sum)

27


In [ ]:
# Write a python program to summ all the items in a list
l1=[2,3,4,5,6,7]
def my_function(l2):
    sum=0
    for x in l2:
        sum+=x
    return sum
print(my_function(l1))


27


In [ ]:
# write a python program to multiply all items in a list

l1=[1,2,3,4,5,6,7,8,9]
product=1
for a in l1:
    product*=a
print(product)

362880


In [ ]:
# Write a python program to find those numbers which are divisible by 7 and multiple of 5,
# between 1500 and 2700

l1=[]
for a in range(1500,2700):
    if (a%7==0)and (a%5==0):
        l1.append(str(a))
print(l1)

['1505', '1540', '1575', '1610', '1645', '1680', '1715', '1750', '1785', '1820', '1855', '1890', '1925', '1960', '1995', '2030', '2065', '2100', '2135', '2170', '2205', '2240', '2275', '2310', '2345', '2380', '2415', '2450', '2485', '2520', '2555', '2590', '2625', '2660', '2695']


In [ ]:
#numpy

In [ ]:
import numpy as np
arr= np.array([1,2,3,4])

print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [ ]:
arr= np.array(43)
print(arr)
print(arr.ndim)

43
0


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)
print(arr.shape[0])

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,23]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 23]]]
3


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[-2])
print(arr[2:])
#start stop step
print(arr[1:5:3])

4
[3 4 5]
[2 5]


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[1,2])
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
3
2


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr= arr.reshape([3,3])
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape([2,2,2])
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
x=np.where (arr%2==0)
print(x)


[1 2 3 4 5 6 7 8 9]
(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
arr=np.array([1,4,7,3,9])
print(np.sort(arr))

arr[::-1].sort()
print(arr)

[1 3 4 7 9]
[9 7 4 3 1]


In [ ]:
from numpy import random
x=random.randint(10)
print(x)

6


In [ ]:
x=random.rand()
print(x)

0.572257861299968


In [ ]:
x=random.randint(100, size=4)
print(x)

[32 35 33 55]


In [ ]:
x=random.randint(100, size=[4,3])
print(x)

[[18 42 37]
 [33 42  1]
 [39 34  8]
 [76 67 57]]


In [ ]:

# pandas 
#  series
# dataframes


In [ ]:
import pandas as pd
a=[1,2,3]
myvar= pd.Series(a,index=["a","b","c"])
print(myvar)
print(type(myvar))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
data={
    "a":[1,2,3,4],
    "b":[5,6,7,8]
}
df=pd.DataFrame(data)
print(df)

   a  b
0  1  5
1  2  6
2  3  7
3  4  8


In [ ]:
df= pd.read_csv('data.csv')

df.head(11)

Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3

In [ ]:
df.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
new_df=df.dropna()
new_df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [ ]:
df=pd.read_csv('data.csv')
df.fillna(100, inplace=True)
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [ ]:
# mean or median imputation

In [ ]:
x=df["Calories"].mean()

df["Calories"].fillna(x, inplace=True)

In [ ]:
x=df["Calories"].median()
df["Calories"].fillna(x,inplace=True)

In [ ]:
df= pd.read_csv('data.csv')
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
164    False
165    False
166    False
167    False
168    False
Length: 169, dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# correlaton

In [ ]:
df.corr()

Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.162098  0.003578  0.923053
Pulse    -0.162098  1.000000  0.787035  0.015301
Maxpulse  0.003578  0.787035  1.000000  0.195309
Calories  0.923053  0.015301  0.195309  1.000000